# Generated by Django 2.2.5 on 2020-04-03 22:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UniversityMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('access_id', models.CharField(max_length=6, unique=True, verbose_name='Access ID')),
                ('legal_name', models.CharField(max_length=100)),
                ('age', models.PositiveSmallIntegerField()),
                ('legal_gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('primary_affiliation', models.CharField(choices=[('1', 'Faculty'), ('2', 'Student')], max_length=1)),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
