# Generated by Django 2.2.5 on 2020-04-06 00:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registrar', '0001_initial'),
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniversityMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('access_id', models.CharField(max_length=6, unique=True, verbose_name='Access ID')),
                ('legal_name', models.CharField(max_length=100)),
                ('age', models.PositiveSmallIntegerField()),
                ('legal_gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('primary_affiliation', models.CharField(choices=[('1', 'Faculty'), ('2', 'Student')], max_length=1)),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ZipcodeInfo',
            fields=[
                ('zipcode', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('state', models.CharField(blank=True, max_length=20)),
                ('city', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TAProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teaching_team', models.PositiveSmallIntegerField()),
                ('office_hours', models.TextField(blank=True)),
                ('office_location', models.CharField(blank=True, max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='TA_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=10)),
                ('home_street_address', models.TextField()),
                ('home_zipcode', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.ZipcodeInfo')),
                ('major_id', models.ForeignKey(default='PMAJ', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='stu_major', to='registrar.Department', verbose_name='Major ID')),
                ('minor_id', models.ForeignKey(null=True, on_delete=models.SET(''), related_name='optional_minor', to='registrar.Department', verbose_name='Minor ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FacultyProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('office', models.CharField(max_length=100)),
                ('department_id', models.ForeignKey(default='PMAJ', on_delete=django.db.models.deletion.SET_DEFAULT, to='registrar.Department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
