# Generated by Django 2.2.5 on 2020-04-03 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='universitymember',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
