# Generated by Django 2.2.5 on 2020-04-06 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('assignment', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('desc', models.TextField(blank=True, verbose_name='Assignment Description')),
                ('detail', models.TextField(blank=True, verbose_name='Assignment Details')),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentGrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.SmallIntegerField(primary_key=True, serialize=False, unique=True)),
                ('course_number', models.CharField(max_length=4)),
                ('course_name', models.TextField()),
                ('credit', models.PositiveSmallIntegerField()),
                ('drop_ddl', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.CharField(default='PMAJ', max_length=5, primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EnrollRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enroll_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FacultyTeachTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teaching_team_id', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_time', models.DateTimeField(auto_now_add=True)),
                ('post_title', models.CharField(default='Untitled', max_length=100)),
                ('post_content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_num', models.PositiveSmallIntegerField()),
                ('capacity_limit', models.PositiveSmallIntegerField(default=30)),
                ('teaching_team_id', models.PositiveSmallIntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registrar.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_time', models.DateTimeField(auto_now_add=True)),
                ('reply_content', models.TextField()),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registrar.Post')),
            ],
        ),
    ]
