# Generated by Django 2.2.5 on 2020-04-13 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registrar', '0002_auto_20200406_0022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facultyteachteam',
            name='id',
        ),
        migrations.AlterField(
            model_name='facultyteachteam',
            name='teaching_team_id',
            field=models.PositiveSmallIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='section',
            name='teaching_team_id',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='registrar.FacultyTeachTeam'),
        ),
    ]
