# Generated by Django 2.2.5 on 2020-04-13 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrar', '0003_auto_20200413_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollrecord',
            name='grade',
            field=models.CharField(choices=[('A', 'A'), ('A-', 'A-'), ('B+', 'B+'), ('B', 'B'), ('B-', 'B-'), ('C+', 'C+'), ('C', 'C'), ('D', 'D'), ('F', 'Failed'), ('IP', 'In Progress')], default='IP', max_length=2),
        ),
    ]
